apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # porta esposta su Minikube (range 30000-32767)
